source: source

name: Nevan Scott
description:
author:
  name: Nevan Scott
  email: nevan@nevanscott.com

timezone: Europe/Madrid
permalink: /:categories/:title/
include: ['.htaccess']
exclude: ['CNAME']

markdown: kramdown
highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  hard_wrap: true
  footnote_backlink: "&#8617;&#xFE0E;"
